[package]
name = "BLANE"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "^0.2"
gtk = "0.9"
ring = "0.16"
glib-sys = "0.10.1"
